version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "task-management-system"
s3_bucket = "task-management-sam-deployment-bucket"
s3_prefix = "task-management-system"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "StageName=\"prod\" AdminEmail=\"admin@example.com\""

[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "task-management-system-dev"
s3_bucket = "task-management-sam-deployment-bucket"
s3_prefix = "task-management-system-dev"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "StageName=\"dev\" AdminEmail=\"admin@example.com\""

[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "task-management-system-prod"
s3_bucket = "task-management-sam-deployment-bucket"
s3_prefix = "task-management-system-prod"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "StageName=\"prod\" AdminEmail=\"admin@example.com\""
