version = 0.1
[staging]
[staging.deploy]
[default.deploy.parameters]
stack_name = "new-task-management"
s3_bucket = "task-management-sam-deployment-bucket"
s3_prefix = "new-task-management"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "StageName=\"dev\" AdminEmail=\"kingsleybotchwayedu11@gmail.com\""
resolve_s3 = true
disable_rollback = true
image_repositories = []

[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "task-management-system-dev"
s3_bucket = "task-management-sam-deployment-bucket"
s3_prefix = "task-management-system-dev"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "StageName=\"dev\" AdminEmail=\"gideon.agbosu@amalitech.com\""

[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "task-management-system-prod"
s3_bucket = "task-management-sam-deployment-bucket"
s3_prefix = "task-management-system-prod"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "StageName=\"prod\" AdminEmail=\"gideon.agbosu@amalitech.com\""