version = 0.1
[default.deploy.parameters]
stack_name = "task-management-test"
resolve_s3 = true
s3_prefix = "task-management-test"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "StageName=\"dev\" AdminEmail=\"kingsleybotchwayedu11@gmail.com\""
image_repositories = []
