AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Task Management System SAM Template

Globals:
  Function:
    Timeout: 30
    Runtime: java21
    MemorySize: 256
    Environment:
      Variables:
        USER_POOL_ID: !Ref UserPool
        USER_POOL_CLIENT_ID: !Ref UserPoolClient
        TASK_TABLE: !Ref TaskTable
        USER_TABLE: !Ref UserTable
        TASK_ASSIGNMENT_TOPIC_ARN: !Ref TaskAssignmentNotificationTopic
        TASK_DEADLINE_TOPIC_ARN: !Ref TaskDeadlineNotificationTopic
        CLOSED_TASK_TOPIC_ARN: !Ref ClosedTaskNotificationTopic
        REOPENED_TASK_TOPIC_ARN: !Ref ReopenedTasksNotificationTopic
        TASK_COMPLETE_TOPIC_ARN: !Ref TaskCompleteNotificationTopic
        TASKS_QUEUE_URL: !Ref TasksQueue
        TASKS_DLQ_URL: !Ref TasksDeadLetterQueue
        USER_ONBOARDING_STATE_MACHINE_ARN: !GetAtt UserOnboardingStateMachine.Arn
        REGION: !Ref AWS::Region

Parameters:
  StageName:
    Type: String
    Description: Environment stage (e.g. dev, staging, prod)
  AdminEmail:
    Type: String
    Description: Email address for the initial admin user

Resources:
  #######################
  # Authentication Resources
  #######################
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub TaskManagementUserPool-${StageName}
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      MfaConfiguration: "OFF"
      Schema:
        - Name: email
          AttributeDataType: String
          Mutable: true
          Required: true
        - Name: role
          AttributeDataType: String
          Mutable: true
          Required: false
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true
        InviteMessageTemplate:
          EmailMessage: "Your username is {username} and temporary password is {####}. Please login to the Task Management System at {##URL##}"
          EmailSubject: "Your Task Management System login details"
      EmailConfiguration:
        EmailSendingAccount: COGNITO_DEFAULT
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
          RequireUppercase: true

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      ClientName: !Sub TaskManagementClient-${StageName}
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_ADMIN_USER_PASSWORD_AUTH
      PreventUserExistenceErrors: ENABLED

  AdminUser:
    Type: AWS::Cognito::UserPoolUser
    Properties:
      UserPoolId: !Ref UserPool
      Username: !Ref AdminEmail
      UserAttributes:
        - Name: email
          Value: !Ref AdminEmail
        - Name: custom:role
          Value: "admin"
      DesiredDeliveryMediums:
        - EMAIL

  #######################
  # Database Resources
  ######################
  TaskTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub TaskManagement-Tasks-${StageName}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: taskId
          AttributeType: S
        - AttributeName: assignedTo
          AttributeType: S
        - AttributeName: status
          AttributeType: S
      KeySchema:
        - AttributeName: taskId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: AssigneeIndex
          KeySchema:
            - AttributeName: assignedTo
              KeyType: HASH
            - AttributeName: status
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "TaskManagement-Users-${StageName}"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: EmailIndex
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  #######################
  # Notification Resources
  #######################
  TaskAssignmentNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub TaskAssignmentNotificationTopic-${StageName}
      DisplayName: Task Assignment

  TaskAssignmentNotificationTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref TaskAssignmentNotificationTopic
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: "*"
            Action:
              - sns:Subscribe
              - sns:Receive
            Resource: !Ref TaskAssignmentNotificationTopic
            Condition:
              StringEquals:
                sns:Protocol: "email"

  TaskDeadlineNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub TaskDeadlineNotificationTopic-${StageName}
      DisplayName: Task Deadline

  ClosedTaskNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ClosedTaskNotificationTopic-${StageName}
      DisplayName: Closed Task

  ReopenedTasksNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ReopenedTasksNotificationTopic-${StageName}
      DisplayName: Reopened Task

  TaskCompleteNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub TaskCompleteNotificationTopic-${StageName}
      DisplayName: Task Complete

  TasksQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub TasksQueue-${StageName}.fifo
      FifoQueue: true
      ContentBasedDeduplication: true
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt TasksDeadLetterQueue.Arn
        maxReceiveCount: 3

  TasksDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub TasksDeadLetterQueue-${StageName}.fifo
      FifoQueue: true
      ContentBasedDeduplication: true

  #######################
  # API Gateway
  #######################
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref StageName
      Auth:
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt UserPool.Arn
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key'"
        AllowOrigin: "'*'"

  #######################
  # Lambda Functions
  #######################

  # Authentication
  CreateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: com.taskmanagementsystem.auth.CreateUserHandler::handleRequest
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - cognito-idp:AdminCreateUser
                - cognito-idp:AdminSetUserPassword
              Resource: !GetAtt UserPool.Arn
            - Effect: Allow
              Action:
                - dynamodb:PutItem
              Resource: !GetAtt UserTable.Arn

            - Effect: Allow
              Action:
                - states:StartExecution
              Resource: !GetAtt UserOnboardingStateMachine.Arn

            - Effect: Allow
              Action:
                - sns:Subscribe
                - sns:Publish
              Resource:
                - !Ref TaskAssignmentNotificationTopic
                - !Ref TaskDeadlineNotificationTopic
                - !Ref ClosedTaskNotificationTopic
                - !Ref ReopenedTasksNotificationTopic
      Events:
        CreateUser:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /users
            Method: post
            Auth:
              Authorizer: CognitoAuthorizer

  AuthenticationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: com.taskmanagementsystem.auth.AuthenticationHandler::handleRequest
      Policies:
        - Version:  "2012-10-17"
          Statement:
            - Effect: Allow
              Action: cognito-idp:InitiateAuth
              Resource: "*"
      Events:
        Authentication:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /auth
            Method: POST

  # Task Management
  CreateTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: com.taskmanagementsystem.tasks.CreateTaskHandler::handleRequest
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
              Resource: !GetAtt TaskTable.Arn
            - Effect: Allow
              Action:
                - sqs:SendMessage
              Resource: !GetAtt TasksQueue.Arn
      Events:
        CreateTask:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /tasks
            Method: post
            Auth:
              Authorizer: CognitoAuthorizer

  GetTasksFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: com.taskmanagementsystem.tasks.GetTasksHandler::handleRequest
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:Query
                - dynamodb:Scan
              Resource:
                - !GetAtt TaskTable.Arn
                - !Sub "${TaskTable.Arn}/index/AssigneeIndex"
      Events:
        GetTasks:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /tasks
            Method: get
            Auth:
              Authorizer: CognitoAuthorizer

  GetTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: com.taskmanagementsystem.tasks.GetTaskHandler::handleRequest
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
              Resource: !GetAtt TaskTable.Arn
      Events:
        GetTask:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /tasks/{taskId}
            Method: get
            Auth:
              Authorizer: CognitoAuthorizer

  UpdateTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: com.taskmanagementsystem.tasks.UpdateTaskHandler::handleRequest
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:UpdateItem
              Resource: !GetAtt TaskTable.Arn
            - Effect: Allow
              Action:
                - sns:Publish
              Resource:
                - !Ref TaskCompleteNotificationTopic
                - !Ref ReopenedTasksNotificationTopic
      Events:
        UpdateTask:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /tasks/{taskId}
            Method: put
            Auth:
              Authorizer: CognitoAuthorizer


  ReassignTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: com.taskmanagementsystem.tasks.ReassignTaskHandler::handleRequest
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:UpdateItem
                - dynamodb:GetItem
                - dynamodb:Query
              Resource:
                - !GetAtt TaskTable.Arn
                - !GetAtt UserTable.Arn
                - !Sub "${UserTable.Arn}/index/EmailIndex"
            - Effect: Allow
              Action:
                - sqs:SendMessage
              Resource: !GetAtt TasksQueue.Arn
            - Effect: Allow
              Action:
                - sns:Publish
                - sns:Subscribe
              Resource: !Ref TaskAssignmentNotificationTopic
      Events:
        ReassignTask:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /tasks/{taskId}/reassign
            Method: post
            Auth:
              Authorizer: CognitoAuthorizer

  # Notifications
  ProcessTaskQueueFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: com.taskmanagementsystem.notifications.ProcessTaskQueueHandler::handleRequest
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - sns:Publish
              Resource: !Ref TaskAssignmentNotificationTopic
            - Effect: Allow
              Action:
                - dynamodb:UpdateItem
              Resource: !GetAtt TaskTable.Arn
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt TasksQueue.Arn
            BatchSize: 1
            FunctionResponseTypes:
              - ReportBatchItemFailures

  TaskDeadlineNotificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: com.taskmanagementsystem.notifications.TaskDeadlineNotificationHandler::handleRequest
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - sns:Publish
              Resource: !Ref TaskDeadlineNotificationTopic
            - Effect: Allow
              Action:
                - dynamodb:Scan
              Resource: !GetAtt TaskTable.Arn

  ProcessExpiredTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: com.taskmanagementsystem.notifications.ProcessExpiredTaskHandler::handleRequest
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - sns:Publish
              Resource: !Ref ClosedTaskNotificationTopic
            - Effect: Allow
              Action:
                - dynamodb:UpdateItem
              Resource: !GetAtt TaskTable.Arn
            - Effect: Allow
              Action:
                - states:StartExecution
              Resource: !GetAtt TaskExpirationStateMachine.Arn

  # Step Functions
  TaskExpirationStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachines/taskExpiration.asl.json
      Type: STANDARD
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:UpdateItem
              Resource: !GetAtt TaskTable.Arn
            - Effect: Allow
              Action:
                - sns:Publish
              Resource: !Ref ClosedTaskNotificationTopic

  UserOnboardingStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachines/userOnboarding.asl.json
      DefinitionSubstitutions:
        TaskAssignmentNotificationTopic: !Ref TaskAssignmentNotificationTopic
        TaskDeadlineNotificationTopic: !Ref TaskDeadlineNotificationTopic
        ClosedTaskNotificationTopic: !Ref ClosedTaskNotificationTopic
        TaskCompleteNotificationTopic: !Ref TaskCompleteNotificationTopic
        ReopenedTasksNotificationTopic: !Ref ReopenedTasksNotificationTopic
      Type: STANDARD
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - sns:Subscribe
              Resource:
                - !Ref TaskAssignmentNotificationTopic
                - !Ref TaskDeadlineNotificationTopic
                - !Ref ClosedTaskNotificationTopic
                - !Ref TaskCompleteNotificationTopic
                - !Ref ReopenedTasksNotificationTopic

  #######################
  # EventBridge Resources
  #######################
  DeadlineReminderRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub TaskDeadlineReminderRule-${StageName}
      Description: "Rule to check for tasks nearing deadline"
      ScheduleExpression: "rate(5 minutes)"
      State: ENABLED
      Targets:
        - Arn: !GetAtt TaskDeadlineNotificationFunction.Arn
          Id: "TaskDeadlineFunction"

  DeadlineReminderPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref TaskDeadlineNotificationFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt DeadlineReminderRule.Arn

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${StageName}"

  UserPoolId:
    Description: "Cognito User Pool ID"
    Value: !Ref UserPool

  UserPoolClientId:
    Description: "Cognito User Pool Client ID"
    Value: !Ref UserPoolClient

  TaskTableName:
    Description: "DynamoDB Task Table Name"
    Value: !Ref TaskTable

  UserTableName:
    Description: "DynamoDB User Table Name"
    Value: !Ref UserTable