package com.taskmanagementsystem.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@DynamoDBTable(tableName = "")
public class Tasks {
    static {
        String tableName = System.getenv("TASK_TABLE");
        if (tableName != null && !tableName.isEmpty()) {
            DynamoDBMapperConfig.Builder builder = DynamoDBMapperConfig.builder();
            builder.setTableNameOverride(DynamoDBMapperConfig.TableNameOverride.withTableNameReplacement(tableName));
            builder.build();
        }
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String taskId;

    @DynamoDBAttribute
    private String name;

    @DynamoDBAttribute
    private String description;

    @DynamoDBAttribute
    private String status;

    @DynamoDBAttribute
    private Long deadline;

    @DynamoDBAttribute
    private String responsibility;

    @DynamoDBAttribute
    private String assignedUserEmail;

    @DynamoDBAttribute
    private Long completedAt;

    @DynamoDBAttribute
    private String userComment;

    @DynamoDBAttribute
    private String createdBy;

    @DynamoDBAttribute
    private Long createdAt;

    @DynamoDBAttribute
    private Long updatedAt;
}
